# installing numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


### Importing numpy

In [2]:
import numpy as np

why use numpy over list 
1. list is very slow and numpy is very fast
2. list require lots of memory and numpy consume less memory



Applications:
1. maths
2. plotting
3. numpu is core componant in pandas
4. ML


# Basics

In [3]:
# creating a np array
a=np.array([2,3,4],dtype='int16')

In [4]:
type(a)

numpy.ndarray

In [5]:
#creating a multi dimensional array
b=np.array([[1,2,3,4],[5,6,7,8]])

In [6]:
type(b)

numpy.ndarray

In [7]:
# get dimension of np array
a.ndim

1

In [8]:
b.ndim

2

In [9]:
# also shape
a.shape

(3,)

In [10]:
# returns (row,col)
b.shape

(2, 4)

In [11]:
# getting data type
a.dtype

dtype('int16')

In [12]:
# get size
a.itemsize

2

# accessing / changing specific elements,row,columns

In [13]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [14]:
# getting a specific index array[row,col] 
a[0][1]

2

In [15]:
# get specific row and all col
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# get specific col
a[:,2]

array([ 3, 10])

In [17]:
# slicing [start:stop:stepsize]
a[0,1:6:2]

array([2, 4, 6])

# initializing the diffrent types of array

In [18]:
# all zeros
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [19]:
# similarly
np.ones((4,2,2),dtype='int16')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [20]:
# any other number matriz np.full((shape),value)
np.full((4,4),4,dtype='int32')

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [21]:
# random num
np.random.random((4,3))

array([[0.67189139, 0.14887552, 0.63689238],
       [0.08566669, 0.81091843, 0.18273071],
       [0.51558914, 0.64667141, 0.50768961],
       [0.44648642, 0.38068856, 0.06821   ]])

In [22]:
# random int
np.random.randint(low=10,high=12,size=(4,4))

array([[10, 11, 10, 10],
       [10, 11, 10, 10],
       [10, 11, 10, 10],
       [10, 11, 10, 10]])

In [23]:
# identity or sq matrix
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

# Maths

In [24]:
a=np.array([2,3,4])

In [25]:
# addes a number to Each Element
a+2

array([4, 5, 6])

In [26]:
a-2

array([0, 1, 2])

In [27]:
a*2

array([4, 6, 8])

In [28]:
a/2

array([1. , 1.5, 2. ])

In [29]:
a%2

array([0, 1, 0], dtype=int32)

In [30]:
b=np.array([4,5,6])

In [31]:
a+b #sums up every element with other arrays resp. ele


array([ 6,  8, 10])

In [32]:
a**2

array([ 4,  9, 16], dtype=int32)

In [33]:
# take sin
np.sin(a)

array([ 0.90929743,  0.14112001, -0.7568025 ])

In [34]:
np.cos(b)

array([-0.65364362,  0.28366219,  0.96017029])

# Linear algebra

In [35]:
a=np.full((2,3),1)
print(a)

[[1 1 1]
 [1 1 1]]


In [36]:
b=np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [37]:
# matrix mul 
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

# statistics

In [39]:
t=np.array([[4,5,6],[66,64,21]])

In [40]:
 t

array([[ 4,  5,  6],
       [66, 64, 21]])

In [45]:
# find min
t.min()

4

In [46]:
# or max
np.max(t)

66

In [50]:
# or on axis basis
np.max(t,axis=0)

array([66, 64, 21])

In [51]:
np.max(t,axis=1)

array([ 6, 66])

In [52]:
#summing all elements in matrix
np.sum(t)

166

In [53]:
# we can also do row and columns in this too
np.sum(t,axis=0)

array([70, 69, 27])

In [54]:
np.sum(t,axis=1)

array([ 15, 151])

In [55]:
# vertically stacking vectors
a=np.array([1,2,3])
b=np.array([6,7,8])

In [57]:
np.vstack([a,b])

array([[1, 2, 3],
       [6, 7, 8]])

In [58]:
# also we can copy them
np.vstack([a,b,a,b,b])

array([[1, 2, 3],
       [6, 7, 8],
       [1, 2, 3],
       [6, 7, 8],
       [6, 7, 8]])

In [59]:
# horizontal stack
a1=np.ones((2,4))
b1=np.zeros((2,2))

In [60]:
np.hstack([a1,b1])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])